services:
  - type: web
    name: taxi-customer-booking-website
    env: static
    buildCommand: ng build --configuration production
    staticPublishPath: dist/taxi-booking-app/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
